### ISSUE TITLE
`queue_shape` uses `path_state_dim` instead of `queue_state_dim`

### ISSUE THREAD

**Issue by zeeros** [BNN-UPC/RouteNet-Erlang#10]
The variable `queue_shape` is using the parameter `path_state_dim` instead of `queue_state_dim`.

https://github.com/BNN-UPC/RouteNet-Erlang/blob/269df1e311a943478df8232f6d009ce474195626/Scheduling/model.py#L123-L129

It makes no difference with the current configuration since `path_state_dim` is equal to `queue_state_dim`.

**Comment by MiquelFerriol** [comment]
Thank you for pointing this out! I have accepted the pull request to solve this.

Also, inspecting the code, I realized the path_state uses the link_state_dim and the linke_state uses the link_state_dim. Both problems have been fixed in the last commit.

Thank you,
Miquel
