### ISSUE TITLE
Checkpoints in `/Scalability/ckpt_dir/` are ignored

### ISSUE THREAD

**Issue by zeeros** [BNN-UPC/RouteNet-Erlang#8]
There are some checkpoints in `/Scalability/ckpt_dir/`, [69-9.91.data-00000-of-00001](https://github.com/BNN-UPC/RouteNet-Erlang/blob/269df1e311a943478df8232f6d009ce474195626/Scalability/ckpt_dir/69-9.91.data-00000-of-00001) and [69-9.91.index](https://github.com/BNN-UPC/RouteNet-Erlang/blob/269df1e311a943478df8232f6d009ce474195626/Scalability/ckpt_dir/69-9.91.index). These are ignored when calling `main.py` to train the model.

```
Starting training from scratch...
```

If this is supposed to showcase a training from a checkpoint, I think a `checkpoint` file is required and it should contain something like the following

```
model_checkpoint_path: "69-9.91"
all_model_checkpoint_paths: "69-9.91"
```

Otherwise they might be just some leftovers, in which case they can be safely deleted.

**Comment by MiquelFerriol** [comment]
Yes, you are right!

It looks like in this TF version you need the `checkpoint` file to detect the "latest" trained checkpoint. Otherwise, it starts from scratch.

The file has been added in the last commit.

Thanks,
Miquel
